config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "users/registrations" }
  get "home/index"
  root "home#index"

  resources :roadmaps, only: %i[index show] do
    post "complete_checkpoint"
    delete "uncomplete_checkpoint"
    post "create_checkpoint"
    resources :checkpoints, only: [:show] do
      member do
        post "create_resource"
        post "rate_resource"
        delete "delete_resource"
      end
    end
  end
end

app/models/roadmap.rb
# == Schema Information
#
# Table name: roadmaps
#
#  id           :bigint           not null, primary key
#  title        :string           not null
#  project_link :string           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Roadmap < ApplicationRecord
  has_many :checkpoints, dependent: :destroy

  validates :title, presence: true
  validates :project_link, presence: true
  validates :project_link,
            format: { with: %r{\A(https?://)?([\da-z.-]+)\.([a-z.]{2,6})([/\w.-]*)*/?\Z}i }
end

app/controllers/roadmaps_controller.rb
class RoadmapsController < ApplicationController
  before_action :authenticate_user!
  before_action :redirect_to_show, only: [:index]
  before_action :set_roadmap, only: %i[show complete_checkpoint uncomplete_checkpoint
                                       create_checkpoint]

  def index; end

  def show; end

  def complete_checkpoint
    if params[:checkpoint_id].present? && @roadmap.checkpoints.find_by(id: params[:checkpoint_id])
      CompletedCheckpoint.create!(user_id: current_user.id, checkpoint_id: params[:checkpoint_id])
      redirect_to roadmap_path(@roadmap)
    else
      redirect_to roadmap_path(@roadmap), alert: "No se envió checkpoint o este es inválido."
    end
  end

  def uncomplete_checkpoint
    if params[:checkpoint_id].present? && @roadmap.checkpoints.find_by(id: params[:checkpoint_id])
      checkpoint = @roadmap.checkpoints.find(params[:checkpoint_id])
      if checkpoint.completed_checkpoints.find_by(user_id: current_user.id).present?
        completed_checkpoint = checkpoint.completed_checkpoints.find_by(user_id: current_user.id)
        completed_checkpoint.destroy!
        redirect_to roadmap_path(@roadmap)
      else
        redirect_to roadmap_path(@roadmap), alert: "No se encontró completed checkpoint válido."
      end
    else
      redirect_to roadmap_path(@roadmap), alert: "No se envió checkpoint o este es inválido."
    end
  end

  def create_checkpoint
    new_checkpoint = Checkpoint.create(
      roadmap_id: params.require(:roadmap_id),
      title: params.require(:checkpoint)[:title]
    )
    if new_checkpoint.errors.any?
      alert_checkpoint = new_checkpoint.errors.full_messages.join(";")
      redirect_to roadmap_path(@roadmap), alert: alert_checkpoint
    else
      redirect_to roadmap_path(@roadmap), notice: "Checkpoint creado"
    end
  end

  private

  def redirect_to_show
    redirect_to roadmap_path(default_roadmap)
  end

  # Ciclo 1 considera sólo 1 Roadmap
  def default_roadmap
    Roadmap.first
  end

  def set_roadmap
    @roadmap = default_roadmap
  end
end

app/helpers/roadmap_helper.rb
# frozen_string_literal: true

module RoadmapHelper
end

app/views/roadmaps/show.html.erb
<h1><%= @roadmap.title %></h1>
<a href="<%= @roadmap.project_link %>" target="_blank">
  Click acá para acceder a su proyecto
</a>
<hr>
<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Checkpoint</th>
      <th scope="col">Completed</th>
    </tr>
  </thead>
  <% @roadmap.checkpoints.each do |checkpoint| %>
  <tbody>
    <tr>
      <th scope="row"> <%= checkpoint.id %> </th>
      <td><a href='<%= roadmap_checkpoint_path(@roadmap,checkpoint) %>' class="checkpoint-link" >
  <%= checkpoint.title %>
</a></td>
      
     
      <td>
      <% if checkpoint.completed_checkpoints.exists?(user_id: current_user.id) %>
        <%= button_to "Completo ✅", roadmap_uncomplete_checkpoint_path(@roadmap,checkpoint_id: checkpoint.id), :class=> "btn btn-outline-light active-checkpoint-button",:method => :delete %>
      <% else %>
        <%= button_to "Incompleto 👮🏻‍♂️", roadmap_complete_checkpoint_path(@roadmap,checkpoint_id: checkpoint.id), :class=> "btn btn-outline-light",:method => :post %>
      <% end %>
      </td>
    </tr>    
  </tbody>
  <% end %>
</table>

<!-- Button trigger modal -->
<% if can? :create_checkpoint, @checkpoint %>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#AddNewCheckpointModal">
  + Nuevo Checkpoint
</button>
<% end %>

<!-- Modal -->
<div class="modal fade" id="AddNewCheckpointModal" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Añade un nuevo checkpoint</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with url: roadmap_create_checkpoint_path(@roadmap), model: Checkpoint, method: "post" do |form| %>
          <%= form.label :label_title, "Título" %>
          <%= form.text_field :title, required: true %>
          <%= form.submit "Crear" %>
        <% end %>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>