config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "users/registrations" }
  get "home/index"
  root "home#index"

  resources :roadmaps, only: %i[index show] do
    post "complete_checkpoint"
    delete "uncomplete_checkpoint"
    post "create_checkpoint"
    resources :checkpoints, only: [:show] do
      member do
        post "create_resource"
        post "rate_resource"
        delete "delete_resource"
      end
    end
  end
end

app/models/checkpoint.rb
# == Schema Information
#
# Table name: checkpoints
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  roadmap_id :bigint           not null
#
class Checkpoint < ApplicationRecord
  belongs_to :roadmap

  has_many :resources, dependent: :destroy
  has_many :completed_checkpoints, dependent: :destroy
  has_many :users, through: :completed_checkpoints

  validates :title, presence: true
  validates :title,
            uniqueness: { scope: :roadmap_id,
                          message: "Ya existe este checkpoint en este Roadmap" }
end

app/controllers/checkpoints_controller.rb
class CheckpointsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_roadmap
  before_action :set_checkpoint

  load_and_authorize_resource

  def show
    @resources_ratings = ResourceRatingCalculator.get_resources_with_average(@checkpoint)
  end

  def rate_resource
    if rate_resource_params.nil?
      redirect_to roadmap_checkpoint_path(@roadmap, @checkpoint),
                  alert: "Error: Recurso no evaluado"
    else
      new_resource_rating = ResourceRating.create(
        user_id: current_user.id,
        resource_id: rate_resource_params[:resource_id].to_i,
        rating: rate_resource_params[:rating].to_i
      )
      if new_resource_rating.errors.any?
        alert = new_resource_rating.errors.full_messages.join(";")
        redirect_to roadmap_checkpoint_path(@roadmap, @checkpoint), alert: alert
      else
        redirect_to roadmap_checkpoint_path(@roadmap, @checkpoint),
                    notice: "Se ha evaluado un recurso!"
      end
    end
  end

  def create_resource
    if new_resource_params.nil?
      redirect_to roadmap_checkpoint_path(@roadmap, @checkpoint), alert: "Error: Recurso no creado"
    else
      new_resource = Resource.create(
        checkpoint_id: @checkpoint.id,
        title: new_resource_params[:title],
        link: new_resource_params[:link]
      )
      if new_resource.errors.any?
        alert = new_resource.errors.full_messages.join(";")
        redirect_to roadmap_checkpoint_path(@roadmap, @checkpoint), alert: alert
      else
        redirect_to roadmap_checkpoint_path(@roadmap, @checkpoint),
                    notice: "Se ha creado un nuevo recurso!"
      end
    end
  end

  def delete_resource
    if params[:resource_id].present? && @checkpoint.resources.find_by(id: params[:resource_id])
      resource = @checkpoint.resources.find_by(id: params[:resource_id])
      deleted_resource = resource.destroy!
      if deleted_resource.errors.any?
        alert = deleted_resource.errors.full_messages.join(";")
        redirect_to roadmap_checkpoint_path(@roadmap, @checkpoint), alert: alert
      else
        redirect_to roadmap_checkpoint_path(@roadmap, @checkpoint),
                    notice: "El recurso ha sido eliminado."
      end
    else
      redirect_to roadmap_checkpoint_path(@roadmap, @checkpoint),
                  alert: "No se encontró recurso o este es inválido."
    end
  end

  private

  def set_roadmap
    @roadmap = Roadmap.find(roadmap_param)
  end

  def set_checkpoint
    @checkpoint = @roadmap.checkpoints.find(params[:id])
  end

  def roadmap_param
    params.require(:roadmap_id)
  end

  def rate_resource_params
    params.require(:resource).permit(:resource_id, :rating)
  end

  def new_resource_params
    params.require(:resource).permit(:title, :link) if params[:resource]
  end
end

app/helpers/checkpoint_helper.rb
# frozen_string_literal: true

module CheckpointHelper
end

app/views/checkpoints/show.html.erb
<h1> <%="Checkpoint: #{@checkpoint.title}"%> </h1>
<br>
<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Recurso</th>
      <th scope="col">Link</th>
      <th scope="col">Current Avg Rating</th>
      <th scope="col">Rate / Your Rating</th>
      <% if can? :destroy, @resource %>
      <th scope="col">Delete Resource</th>
      <% end %>
    </tr>
  </thead>
  <% @resources_ratings.each do |resource|%>
  <tbody>
    <tr>
      <th scope="row"> <%= resource[:id] %> </th>
      <td> <%= resource[:title] %></td>
      <td> <a class="btn btn-secondary" href=<%= resource[:link] %> target="_blank">Go!</a> </td>
      <td> <%= resource[:average_rating] %> </td>
      <td>
      <% if current_user.resource_ratings.find_by(resource_id: resource[:id]).present? %>
        <%= current_user.resource_ratings.find_by(resource_id: resource[:id]).rating %>
      <% else %>
        <%= form_with url: rate_resource_roadmap_checkpoint_path(@roadmap, @checkpoint), model: Resource.find(resource[:id]), method: "post" do |form| %>
          <%= form.hidden_field :resource_id, value: resource[:id] %>
          <%= form.number_field :rating, in: 1..5, step: 1, required: true,  :class => 'input-rating' %>
          <%= form.submit "Evaluar", :class => 'btn btn-primary evaluate-button' %>
        <% end %>
      <% end %>
      </td>
      <% if can? :destroy, @resource %>
        <td>
          <%= button_to "X", delete_resource_roadmap_checkpoint_path(@roadmap, @checkpoint, resource_id: resource[:id]), :class=> "btn btn-danger",:method => :delete %>
        </td>
      <% end %>
    </tr>
  </tbody>
  <% end %>
</table>

<div class="columns">
  <div class="column">
    <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#AddNewResourceModal">
        + Nuevo recurso
      </button>
  </div>
  <div class="column">
    <!-- Button back -->
    <%= button_to "VOLVER", roadmap_path(@roadmap), :class => "btn btn-warning", :method => :get %>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="AddNewResourceModal" tabindex="-1" aria-labelledby="resourceModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Añade un nuevo recurso</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with url: create_resource_roadmap_checkpoint_path(@roadmap, @checkpoint), model: Resource, method: "post" do |form| %>
          <%= form.label :label_title, "Título" %>
          <%= form.text_field :title, required: true %>
          <%= form.label :label_link, "Link" %>
          <%= form.url_field :link, required: true %>
          <%= form.submit "Crear" %>
        <% end %>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>