config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "users/registrations" }
  get "home/index"
  root "home#index"

  resources :roadmaps, only: %i[index show] do
    post "complete_checkpoint"
    delete "uncomplete_checkpoint"
    post "create_checkpoint"
    resources :checkpoints, only: [:show] do
      member do
        post "create_resource"
        post "rate_resource"
        delete "delete_resource"
      end
    end
  end
end

app/views/layouts/_flash.html.erb
<br>
<% flash.each do |name, msg| %>
  <% if name == "notice"  %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= content_tag(:div, msg) %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% elsif name == "alert" %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= content_tag(:div, msg) %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="#">---The Kawe---</a>
  <% if current_user %>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Home", roadmaps_path,class: "nav-link btn" %>
        </li>
      </ul>
    </div>
  <% end %>
  <div class="flex-row-reverse ">
    <ul class="navbar-nav" style="padding-right: 10px">
      <% if !current_user %>
      <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class:"nav-link btn"%>
      </li>
      <% else %>
        <li class="nav-item">
          <p style="padding: 8px; margin-bottom: 0px"> <span style="color: rgba(255, 255, 255, 0.55); vertical-align: middle"> Usuario: <%= current_user.name %> </span> </p>
        </li>
        <li class="nav-item">
          <p style="padding: 8px; margin-bottom: 0px"> <span style="color: rgba(255, 255, 255, 0.55); vertical-align: middle"> Rol: <%= current_user.role %> </span> </p>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, class:"nav-link btn", data: { "turbo-method": :delete } %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>Kawe</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= render 'layouts/flash'%>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>